[FEAT] 분리 및 이관 User 도메인 데이터 생성
sopt-makers/sopt-operation-backend pull request #257
Opened 2024-05-22 12:48 UTC by yummygyudon

## Related Issue 🚀
- closed #256 
- closes T-10853

## Work Description ✏️
- 플레이그라운드로부터 분리 및 이관해오는 User 관련 데이터에 대한 Table & 그에 따른 Entity 를 생성했습니다.
- Enumerated 속성은 아래와 같습니다. 
  - `Gender` : 성별
  - `Part` : 파트
  - `Position` : 활동 직위
  - `SocialType` : 가입 소셜 플랫폼
  - `Team` : 활동 소속 팀 

## PR Point 📸

2024-05-23 01:24 UTC, KWY0218 requested changes
작업하시느라 고생하셨습니다!
중간 중간 반영해야 할 부분이 있기 때문에 request change 했습니다

2024-05-23 01:24 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/User.java
> +    private LocalDate birthday;
p3
LocalDate라고 저장해도 DB에는 Date 타입으로 들어가는 것으로 알고 있습니다.
혹시 converter를 따로 사용하는 이유가 있을까요?

2024-05-23 01:24 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/UserGenerationHistory.java
> +    private Integer integer;
p1
integer가 아닌 generation으로 수정해야 합니다

p3
int가 아닌 Integer를 사용하는 이유가 있을까요?
저는 개인적으로 원시 타입을 쓰는 편을 선호하는데,
왜냐면 객체 타입을 사용하면 WAS 내에서 null 이 들어갈 가능성도 있기 때문에
원시타입을 사용해서 아예 배제하려고 하는 편입니다..!
어떻게 생각하시나요?!

2024-05-23 01:24 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/UserRegisterInfo.java
> +    private Part part;
p1

Enumerate 반영해주세요!

2024-05-23 01:24 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/UserRegisterInfo.java
> +    private Integer generation;
p3
해당 내용도 위와 같습니다

2024-05-23 01:24 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/Team.java
> +    MAKERS
p3
MAKERS 제외하는 걸로 결론지은 거로 알고 있는데 혹시 넣은 이유가 있을까요?

2024-05-23 01:24 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/Part.java
> +}
P1
파트 내용 반영해주세요!

2024-05-23 05:11 UTC, KWY0218 commented
@yummygyudon 
또 생각난건데, 혹시 유저 프로필은 플그랑 합의하에 플그쪽으로 넘어간 것일까요..?

2024-05-23 16:08 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/UserGenerationHistory.java
> +    private Integer integer;
> integer가 아닌 generation으로 수정해야 합니다

이런....어이없는 실수를 했네요.. 바로 반영했습니다.

<br/>

> int가 아닌 Integer를 사용하는 이유가 있을까요?

혹시나하는 Nullable한 상황을 대비하는 차원에서 Integer 타입으로 선언했습니다만
현재 도메인 설계측면에서 고려했을 때,
항상 not null을 보장해야하네요.

`int`로 반영했습니다.

2024-05-23 16:09 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/User.java
> +    private LocalDate birthday;
> converter를 따로 사용하는 이유가 있을까요?

LocalDate 에서 Date로 자동 변환이 되는데 굳이 필요하진 않겠네요...!!
수정 반영했습니다.

2024-05-23 16:13 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/Team.java
> +    MAKERS
> MAKERS 제외하는 걸로 결론지은 거로 알고 있는데 혹시 넣은 이유가 있을까요?

사실 상 MAKERS 라는 enum 값을 사용하지 않으면 문제 발생 가능성이 낮을 것이라고 생각해서
추후 반영하고자 값이기에 냅둬보자 라는 생각으로 값을 냅뒀는데요...!!

우선 지우는게 맞는 판단일 것 같네요!!

2024-05-23 16:25 UTC, yummygyudon commented
> @yummygyudon 또 생각난건데, 혹시 유저 프로필은 플그랑 합의하에 플그쪽으로 넘어간 것일까요..?

이거는 조금 더 얘기를 나눠보고 반영 해보겠습니다!

2024-05-24 03:24 UTC, KWY0218 commented
@yummygyudon 
작업하시느라 고생하셨습니다..!
그러면 유저 프로필 관련 합의가 된 이후에 어푸르브 달겠습니다..!

2024-05-28 09:18 UTC, merged