T-10855 [feat]
sopt-makers/sopt-operation-backend pull request #260
Opened 2024-05-29 11:55 UTC by KWY0218

## Related Issue 🚀
- closed #258 

## Work Description ✏️
1. external 모듈 내 소셜 로그인 기능 구현

## PR Point 📸
1. Auth Controller 내부에서 Social Login Manger를 이용하여 소셜 로그인을 진행하려 합니다.
    추상화를 통해 공통된 로직을 분리하려 했으나, 해당 방식은 확장성을 방해한다고 생각하여
    소셜 로그인 별로 class 를 만들었습니다.
    [ex. 소셜 로그인 변경 or 소셜 로그인 중 open id 방식을 지원하지 않을 수 있음 ]

2024-05-29 19:42 UTC, yummygyudon requested changes
@KWY0218 고생 많으셨어요!! ☺️

몇 몇 부분은 P2 ~ P3 리뷰도 있지만
작고 소중한(?) 사소한 P4 리뷰도 몇 개 있으니 편하게 봐주세요!!

2024-05-29 19:42 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +        return platformCode;
`P3`

`putIfAbsent()` 메서드의 경우 처리한 다음, 저장된 값을 반환해주기 때문에
**바로 return** 해도 괜찮을 것 같다고 생각하는데 다른 의도가 있으셨던 것인지 궁금합니다!!

2024-05-29 19:42 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthServiceImpl.java
> +    private final ValueConfig valueConfig;
`P4`

필드 선언 시의 개행 규칙이 모호한 것 같습니다!!

`static final`과 `final`을 구분하기 위해 하는 것이 더 가독성 높을 것 같아요!!
더불어 "`class` - `field`" & "`field` - `method`" 선언 사이에 1줄씩 정도 개행해 줘도 좋을 것 같네요!!

2024-05-29 19:42 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthServiceImpl.java
`P2`

앞서 리뷰했던 if 블럭 리뷰 내용과 동일합니다! :)

2024-05-29 19:42 UTC, yummygyudon commented on operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/AuthFailureCode.java
> +    // 400
`P4`

별 건 아니구 `class`와 내부 내용 사이에 개행!!
```suggestion
public enum AuthFailureCode implements FailureCode {

    // 400
```

2024-05-29 19:42 UTC, yummygyudon commented on operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/AuthFailureCode.java
> +    // 404
`P4`

개행하면 조금 더 가독성 좋을 것 같습니다!!
```suggestion
    FAILURE_READ_PRIVATE_KEY(BAD_REQUEST, "Private key 읽기 실패"),
    
    // 404
```

2024-05-29 19:42 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/TeamOAuthInfo.java
> +}
`P4`

가독성을 위한 개행!!
```suggestion
public class TeamOAuthInfo {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    private Long id;
    
    @Column(name = "client_id", nullable = false)
    private String clientId;
    
    @Column(name = "redirect_uri", nullable = false)
    private String redirectUri;
    
    @Column(name = "team", nullable = false)
    @Enumerated(EnumType.STRING)
    private Team team;
    
}
```

2024-05-29 19:42 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/TeamOAuthInfo.java
> +@Entity
`P2`

1. 별 다른 Builder를 사용하지 않은 이유가 따로 있을까요??
2. 해당 객체에 대한 Getter의 필요성은 없을까요?

2024-05-29 19:42 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/SocialType.java
> +                .anyMatch(socialType -> socialType.name().equals(type));
`P3`

지역 변수 선언을 한 이유가 따로 있는지 궁금합니다!!
물론 사소하지만 불필요한 변수 선언으로 저장 공간 낭비가 있을 것 같아서요!!

---
또한 String으로 `name()`과 `euals()` 연산하는 것보다
객체 비교를 하는 것이 논리적 오류 발생 위험성이 상대적으로 적다고 들었습니다!

아래와 같이 개선하면 어떨까 생각하는데 원용님의 의견이 궁금해요!!
```suggestion
        return Arrays.stream(SocialType.values())
                .anyMatch(socialType -> socialType.equals(SocialType.valueOf(type)));
```

2024-05-29 19:42 UTC, yummygyudon commented on operation-external/src/main/java/org/sopt/makers/operation/client/social/GoogleSocialLogin.java
`P1`

AppleSocialLogin 클래스에서도 마찬가지로 재사용되는 값들이 존재하는 것 같아요!!
이에 상수값을 별도 클래스에서 관리하는 것은 어떨지 제안드려봅니다!! 

더불어 특정 클래스에서만 사용하는 값들에 대해서도
가독성 & 재사용성을 위해 매직 String으로 관리하는 것은 어떨지 제안드려봅니다!!


1. 재사용되는 상수 값
   -  요청 Parameter Key ( ex. `authorization_code` , `client_id`, `code`, `grant_type`, `redirect_uri` )
   - Jwt 요소들의 Key (ex. `kid`, `alg`, ..)
```java
public abstract class AuthRequestParameterKey {

    public static final String AUTHORIZATION_CODE = "authorization_code";
    public static final String CLIENT_ID = "client_id";
    public static final String GRANT_TYPE = "grant_type";
    public static final String REDIRECT_URI = "redirect_uri";

}
```

2. 요청 Host
   - 훨씬 명시적으로 변수의 역할을 표현할 수 있을 것 같아요!!
```java
public class GoogleSocialLogin {

    private static final String GOOGLE_TOKEN_HOST = "https://oauth2.googleapis.com/token";
```
혹은 아예 관심사에 따라 상수값을 관리하고 싶다면
```java
public abstract class ExternalAuthPlatformInfo {

    public static final String GOOGLE_TOKEN_HOST = "https://oauth2.googleapis.com/token";
    public static final String APPLE_TOKEN_HOST = "https://appleid.apple.com/auth/token";
```

2024-05-30 00:09 UTC, KWY0218 commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +    private boolean checkParamsIsNull(String... params) {
list로 받는다면 비즈니스 로직에 별도의 list 생성 로직을 만들어야 하고

또한 매개 변수로 받으면 4개의 if문이 생기기 때문에 가변 인자 방식을 사용했습니다

2024-05-30 00:31 UTC, KWY0218 commented on operation-external/build.gradle
> +    implementation 'org.bouncycastle:bcpkix-jdk18on:1.75'
db6fa35, 87f5f62
해당 커밋에 남겼습니다! 확인 부탁드려요!

2024-05-30 00:33 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/SocialType.java
> +                .anyMatch(socialType -> socialType.name().equals(type));
SocialType.valueOf 를 하지 않고 해당 메서드를 만든 이유는 type이 만약에 'GOOGLE', 'APPLE'이 아닌 다른 문자열이 들어왔을 때 IilgalException을 반환하기 때문입니다.

그래서 SocialType의 arrays를 받은 이후 해당 arrays 내에 값이 없으면 false를 반환하도록 구현했습니다

2024-05-30 00:33 UTC, KWY0218 commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +    private boolean checkParamsIsNull(String... params) {
not null annotation 적용하는 거 좋은 것 같네요~!

2024-05-30 01:36 UTC, KWY0218 commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +        if (!SocialType.isContains(type)) throw new AuthException(INVALID_SOCIAL_TYPE);
1.
제가 기억하진 못하는 걸수도 있는데 요런 컨벤션을 정했는지 몰랐네요..! 흠.. 하지만 한줄을 위해 `{  }` 을 하는 것은 로직 길이가 더 길어져서 지양하고 싶단 생각이 드는데 혹시 어떻게 생각하시나요?

2.
controller 단에서는 사용자로부터 들어온 값을 검증하고, 서비스 단에서는 db에서 가져오는 값을 검증했습니다..!

이를 통해서 서비스 단의 검증 부담을 줄이려 했습니다. 이런식으로 분리하려 하는데 혹시 어색한 점 있을까요..?

2024-05-30 01:41 UTC, KWY0218 commented on operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/TeamOAuthInfo.java
> +@Entity
1. 해당 엔티티는 db를 통해 insert하기 때문에 save 등을 사용하지 않아 entity를 생성할 일이 없기 때문에 만들지 않았습니다

2. getter 또한 jpa query문을 통해 충분히 검증할 수 있기 때문에 만들지 않았습니다

위 builder 및 getter 모두 추후 필요한 상황이 생긴다면 만들 것 같습니다.

2024-05-30 01:42 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/social/GoogleSocialLogin.java
관심사에 따라서 상수 처리 반영하겠습니다~!

2024-05-30 12:38 UTC, KWY0218 commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +        return platformCode;
만약 해당 map 내부에 동일한 값이 있을 땐, **null을 반환**하기 때문에 인가 코드를 무조건 반환하기 위해서 바로 return을 하지 않았습니다!

2024-05-30 12:53 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/social/GoogleSocialLogin.java
key 값을 제외한 value 값들은 모두 상수화 진행했습니다.
key 값들은 상수화를 안하는 것이 코드를 읽을 때 더욱 가독성이 좋을 것 같다고 생각해서 key 값들은 상수화를 진행하지 않았습니다..!

2024-05-30 17:16 UTC, yummygyudon approved these changes
확인 마쳤습니다!!
고생 정말 많으셨어요!! ❤️

별건 아니지만.. 사소한 개행에 대한 리뷰에 대한 답변이 없는 듯하여
이에 대한 원용님의 의견이 궁금하다는 말과 함께 마치도록 하겠습니당ㅋㅋ

2024-05-30 17:16 UTC, yummygyudon commented on operation-domain/src/main/java/org/sopt/makers/operation/user/domain/SocialType.java
> +                .anyMatch(socialType -> socialType.name().equals(type));
좋아요!! 중간 연산에 대해서는 기존에 PR 올리신대로 처리해도 좋을 것 같습니다!!

++ 불필요한 메서드 내 지역변수 선언만 `stream()` 안에서 처리해주시면 감사드리겠습니다!! 🙇‍♂️

2024-05-30 17:16 UTC, yummygyudon commented on operation-external/build.gradle
> +    implementation 'org.bouncycastle:bcpkix-jdk18on:1.75'
오우 제가 커밋 메세지 바디를 읽지 않아서 놓친거군요!!
감사합니다!! ❤️

2024-05-30 17:16 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +        return platformCode;
확인했습니다!! 감사해요 :)

2024-05-30 17:16 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
> +    private boolean checkParamsIsNull(String... params) {
하긴 검증용으로 별도 Custom Annotation을 생성 및 구현해서 
의도한 예외를 처리하는 방식을 가져가기에는
일정이 타이트한 현재 시점에서 부담스러울 수 있겠네요!!

(추후에 별도 PARAMETER 타겟의 Argument Resolver 어노테이션을 구현해서 사용하면 훨씬 Controller 메서드의 가독성이 좋아질 것 같아요!!)

2024-05-31 00:42 UTC, KWY0218 commented
@yummygyudon 
운영 프로덕트 팀 코딩 컨밴션을 다시 보니 제가 어기고 있었네요..!
개행 및 한줄 if 문 모두 반영했습니다!!

2024-05-31 09:33 UTC, merged