[FEAT] 알림 예약 발송 / 즉시 발송 API 구현
sopt-makers/sopt-operation-backend pull request #274
Opened 2024-06-27 05:18 UTC by yeseul106

## Related Issue 🚀
- closed #255 

## Work Description ✏️
- 일단 PR 볼륨이 큰 것 같아서 죄송합니다 ㅠㅠ Alarm 구조를 지금 기능에 맞게 개선하니까 엮여있는 부분이 많아서 즉시 발송와 예약 발송을 한번에 올린 점 양해 부탁드립니다 !
- Alarm 엔티티 구조 바꿨습니다. 안쓰는 레거시 컬럼은 제외하고, 필요한 컬럼들은 추가 하였습니다.
- 예약 발송 : EventBridge의 일회성 일정을 생성하여 기존에 구현되어 있는 푸시 알림 Lambda 함수를 특정 시간에 호출하도록 구현하였습니다.
- 즉시 발송 : 기존에는 알림 생성 -> 알림 전송의 Flow 였는데, 이번에 기능이 Update 되면서 즉시 발송으로 바뀌었습니다. 이에 따라 알림을 바로 발송하도록 기존 코드를 수정했습니다.
- 예약 발송의 경우, 특정 시간이 되어서 예약 발송이 완료되면 해당 알림의 status를 바꾸는 로직이 구현되어 있지 않습니다. 이는 따로 이슈 파서 회의 때 나온 내용 기반으로 outBound 규칙을 통해  추후 구현하겠습니다.

## PR Point 📸

- 대부분 기존 코드의 컨벤션을 따라서 구현하고자 했습니다.
- import 문 관련해서 저희 컨벤션 얘기를 잠깐 했었던거 같은데, wildcard 말고 그 정렬인가 관련해서 잘 기억이 안나서 이거 관련되어서 잘못된 부분 있으면 말씀해주세요 ! ㅎㅎㅎ

2024-06-28 07:41 UTC, yummygyudon requested changes
1차 코드리뷰 마쳤습니다!!

우선 이동해야할 일이 있어서 잠시 후에 마저 코드리뷰 해보도록 하겠습니다!!

전체적으로 메서드의 "Parameter 개행 처리" 조금만 신경써주시면 좋을 것 같아요!!
고생하셨습니다!!

2024-06-28 07:41 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApi.java
`P2`

알림을 조회하는 API & 알림을 삭제하는 API의 메서드명이 `getAlarm` & `deleteAlarm`인 것으로 인지했는데요!
이에 따라 HTTP Method 이름으로 통일하면 더 가독성과 의미 전달이 용이해지지 않을까 싶어요!!

또한 즉시 알림 등록 API / 예약 알림 등록 API 모두 알림 서버로 POST 하는 API라고 생각하며 "post"로 귀결된다고 생각하여
아래와 같은 네이밍 변경 제안드려봅니다!!

- 즉시 발송 알림 등록 : `sendAlarm` -> `postInstantAlarm` or `postDirectAlarm`
- 예약 발송 알림 등록 : `scheduleAlarm` ->  `postScheduledAlarm` or `postReservedAlarm`

예슬님 의견도 편하게 말씀주세요!!

2024-06-28 07:41 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApiController.java
`P4`

HTTP Method 순서를 섞어놓으신 이유가 따로 있으신가요? (`Post` -> `Get` -> `Get` -> `Delete` -> `Post`)
같은 HTTP Method를 연속적으로 배치하면 조금 더 확인하기 용이할 것 같아요!!
만약 Controller Method가 늘어난다면 더더욱이요!!

특별한 이유가 있다면 말씀해주세요!!

2024-06-28 07:41 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmInstantSendRequest.java
`P1`

몇 몇 필드들이 Non Null이어야 하는 것으로 알고 있어요!!
Controller에 별다른 `@Valid` 나 본 Request DTO 필드에 `@NonNull`등의 유효성 검사 어노테이션을 등록하면 좋을 것 같다고 생각합니다!!

또한 PM님과 논의하여 Title / Content 등에 글자 수 제한이 없는지 확인한 후, 이 또한 유효성 검사를 진행하면 좋을 것 같아요!!

2024-06-28 07:41 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmScheduleSendRequest.java
`P1`

`AlarmInstantSendRequest.java` DTO record 객체에 등록한 리뷰 내용과 동일한 내용입니다!

2024-06-28 07:41 UTC, yummygyudon commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/dto/EventBridgeSenderRequestBody.java
> +                                           String webLink) {
`P5`

파라미터 개행이 조금 보기 어려운 느낌이에요 ㅠㅜ

```java
public record EventBridgeSenderRequestBody(
            List<String> userIds,
            String title,
            String content,
            Category category,
            String deepLink,
            String webLink
) {
    ....
}
```

2024-06-28 07:41 UTC, yummygyudon commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/dto/EventBridgeSenderRequestHeader.java
> +        return new EventBridgeSenderRequestHeader(action, xApiKey, transactionId, "operation");
`P3`

`"operation"` 값 또한 밖에서 주입 시켜주는 것은 어떨까 싶어요!!
해당 static 생성자 메서드를 호출하는 `EventBridgeSenderRequest.java` 내의 Header에 주입하는 `x-api-key` 값과 함께 관리하면 어떨까요?!!

```java
// EventBridgeConstValue.class
public abstract class EventBridgeConstValue {
    public static String HEADER_SERVICE = "operation";
    public static String HEADER_X-API-KEY = ".....";
}


// EventBridgeSenderRequest.java
static import ......EventBridgeConstValue;
public static EventBridgeSenderRequest of(
            String action,
            List<String> userIds, String title, String content, Category category, String deepLink, String webLink
    ) {
        val header = EventBridgeSenderRequestHeader.of(HEADER_X-API-KEY, action);
        EventBridgeSenderRequestBody Body = EventBridgeSenderRequestBody.of(userIds, title, content, category, deepLink,
                webLink);
        return new EventBridgeSenderRequest(Header, Body);
    }
}

// EventBridgeSenderRequestHeader.java
static import ......EventBridgeConstValue;
public static EventBridgeSenderRequest of(
            String action,
            List<String> userIds, String title, String content, Category category, String deepLink, String webLink
    ) {
        val header = EventBridgeSenderRequestHeader.of(HEADER_SERVICE, action);
        EventBridgeSenderRequestBody Body = EventBridgeSenderRequestBody.of(userIds, title, content, category, deepLink,
                webLink);
        return new EventBridgeSenderRequest(Header, Body);
    }
}
```

2024-06-28 07:41 UTC, yummygyudon commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/dto/EventBridgeSenderRequestHeader.java
`P1`

- 변수명 첫 글자 대문자 소문자로 바꿔주세요!! `Header` -> `header`
- `lombok.val` 활용해주세요!

2024-06-30 08:08 UTC, yummygyudon requested changes
고생 많으셨습니다!! ❤️
몇 가지 요소에 대해 예슬님의 의견과 더불어 의사결정 및 반영 완료되시면 말씀주세요!!
추가 리뷰 진행 이후 Approve 하도록 하겠습니다!!

추가적으로
AlarmService 객체 내부에 `AlarmSender` 와 `EventBridgeSender`가 모두 주입되어
관심사가 혼재된 듯한 구조에 대한 개선안은 구두로 전달드렸으니
만약 이 부분에 대해 제 의견이 궁금하신 부분이 있으시거나 추가 제안 주실 내용있으면 언제든 멘션/연락 주시면 감사드리겠습니다!!

2024-06-30 08:08 UTC, yummygyudon commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/service/AlarmServiceImpl.java
> +        val deepLink = linkType == LinkType.APP ? request.link() : null;
`P2`

이부분에 대해서는 기존 `AlarmSenderImpl.java` 내에서 `AlarmSenderRequest`객체에서 getter 메서드(`.link()`)를 통해 주입해주는 부분이 있는데 
해당 객체의 link 필드가 nullable해서 자동으로 위와 같이 연산되어 들어가는 방식입니다!! 
> 참고
```java
// AlarmSenderImpl.java 코드 일부 발췌
	private Map<Object, Object> getAlarmRequest(AlarmSenderRequest request) {
		val alarmRequest = new HashMap<>();
		val link = request.link();
		val linkKey = getLinkKey(link);

		if (!linkKey.isEmpty()) {
			alarmRequest.put(linkKey, link);
		}
		...
	}

	private String getLinkKey(String link) {
		val appLinkList = valueConfig.getAPP_LINK_LIST();
		val webLinkList = valueConfig.getWEB_LINK_LIST();

		if (nonNull(link)) {
			if (appLinkList.contains(link)) {
				return "appLink";
			} else if (webLinkList.contains(link)) {
				return "webLink";
			}
		}
		return "";
	}
```
따로 처리해주신 이유가 있으실까요?!

2024-06-30 08:08 UTC, yummygyudon commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +                    .build();
`P3`

`Target` 객체를 생성하는 로직과 `CreateScheduleRequest` 객체를 생성하는 메서드들은
private 메서드로 분리해서 가독성을 개선할 수 있을 것 같아요!!

2024-06-30 08:15 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApi.java
네 저도 동의합니다 ! 해당 사항 반영할게요 ~!

2024-06-30 08:16 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApiController.java
지금 현재 구조는 `Post` -> `Post` -> `Get` -> `Get` -> `Delete` 로 같은 메서드끼리 연속 배치되도록 구현한 것 같은데 혹시 제가 이해를 잘 못한걸까요 ...?!?!

2024-06-30 08:17 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApiController.java
>  import org.springframework.data.domain.Pageable;
아하 제가 놓쳤던 import 관련 컨벤션이 이거였군요 !!! 네네 ! 신경쓰겠습니다 ~!

2024-06-30 08:17 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmInstantSendRequest.java
넵 이거 한번 기획 문서 확인해보고 추가해둘게요 !

2024-07-01 01:12 UTC, KWY0218 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApi.java
흠.. 저는 _'알림을 조회하는 API & 알림을 삭제하는 API의 메서드명이 getAlarm & deleteAlarm'_ 이라 작성한 건 HTTP Method 이름을 사용한 것이 아니라 해당 함수의 역할을 말하는 것이 아닐까란 생각이 들어요.

그래서 postInstantAlarm 보다는 sendInstantAlarm과 같이 send를 붙이는 것이 더욱 해당 함수가 어떤 역할을 하는지 명시한다고 생각하는데요.

또한, 어노테이션으로 해당 함수가 어떤 메서드인지 알 수 있기 때문에 함수명으로는 해당 함수의 역할을 더 설명해주는 쪽이 좋지 않을까란 생각이 듭니다..!

2024-07-01 01:52 UTC, KWY0218 reviewed
작업 고생하셨습니다!
코맨트 확인해주세요!

2024-07-01 01:52 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +            String scheduleName = String.format("%s_%s_%d", postDate, formattedTime, alarmId);
p2
해당 class 파일 내부에 변수를 선언할 때 lombok의 `val` 를 통해 변수를 생성해주세요!

2024-07-01 01:52 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +    private ObjectMapper objectMapper;
p2 

```suggestion
@Component
@RequiredArgsConstructor
public class EventBridgeImpl implements EventBridgeSender {

    private SchedulerClient schedulerClient;
    private final ValueConfig valueConfig;
    private ObjectMapper objectMapper;
```
첫 문장을 개행하는 컨밴션이 있습니다! 참고해주세요!

2024-07-01 01:52 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +        try {
p2
해당 함수가 public static인 이유가 있을까요?

2024-07-01 01:52 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +            String eventJson = String.format("{\"detail\": %s}", objectMapper.writeValueAsString(request));
p3
해당 eventJson 은 무슨 용도인지 궁금합니다.

2024-07-01 01:52 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/dto/EventBridgeSenderRequest.java
> +            List<String> userIds, String title, String content, Category category, String deepLink, String webLink
p4
왜냐하면 해당 request를 만들 때 xApiKey를 생성자로 받아야 하는지 궁금하기 때문입니다.

해당 request를 생성하는 class 파일과 사용하는 class 파일은 모두 value config가 정의 되어 있는데, eventJson을 만들기 위해 꼭 필요한 형식이기 때문에 아규먼트로 받는 것인지 이유가 궁금합니다..!

2024-07-01 02:34 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApi.java
저도 함수의 동작을 설명하기 위해서 send를 붙인 거긴 해서요..! 그럼 즉시와 예약을 구분하는 Instant와 schedule은 명시하되, post 말고 send로 통일하는건 어떨까요 ?! @KWY0218 @yummygyudon

2024-07-01 02:34 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApiController.java
이해 했습니다 ! 해당 순서로 재배치 할게요 ~

2024-07-01 02:38 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/service/AlarmServiceImpl.java
이거는 기존에 구현되어있는 코드에서 제가 따로 건들인 건 없었는데요 ! `@Transactional(readOnly=true)` 가 원래 누락이 되었던 것 같은데 제가 추가 해놓을게요 !

2024-07-01 02:45 UTC, yeseul106 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/service/AlarmServiceImpl.java
> +        val deepLink = linkType == LinkType.APP ? request.link() : null;
위의 코드는 기존 뷰에서 링크 첨부란이 없었을 때 구현되어 있는 코드였습니다 ! 하지만 바뀐 뷰에서는 링크 타입을 지정하고 링크를 첨부할 수 있게 바뀌었기 때문에 그에 맞게 처리를 해주었습니다.

또한 AlarmSenderRequest는 알림서버에 보내는 request DTO 형식이라서, eventBridge에 보내는 request DTO와는 차이가 있어 생성하는 로직이 구분되어있습니다 !

2024-07-01 02:45 UTC, yeseul106 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +    private ObjectMapper objectMapper;
네 ! 감사합니다 ! 신경쓰겠습니다 !!

2024-07-01 04:01 UTC, KWY0218 commented on operation-api/src/main/java/org/sopt/makers/operation/web/alarm/api/AlarmApi.java
저는 좋습니다..!

2024-07-01 17:01 UTC, yeseul106 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/dto/EventBridgeSenderRequestHeader.java
> +        return new EventBridgeSenderRequestHeader(action, xApiKey, transactionId, "operation");
현재 모든 환경 변수 값들은 ValueConfig 한 곳에서 관리하고 있기 때문에 해당 클래스에 정의해두도록 하겠습니다 !

2024-07-01 17:11 UTC, yeseul106 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +            String eventJson = String.format("{\"detail\": %s}", objectMapper.writeValueAsString(request));
PR description에도 써놓았지만, 현재 구현된 푸시 알림 서버로 요청을 보낼 때는 header와 body를 정해진 규격에 맞춰서 값을 보내야 알림 서버에서 구현된 코드에 맞게 푸시 알림이 전송됩니다 !

이 때 현재 예약 알림의 경우. 이벤트 브릿지를 통해 일정을 생성한 뒤 해당 시간이 되면 푸시 알림 서버로 요청이 들어가는데 header와 body를 페이로드 값으로 넘길 수 있어야 정상적으로 알림 서버에 구축된 기존 로직에 따라 동작하기 때문에 이를 json 형식으로 바꿔서 input 데이터로 넣어주기 위함입니다 !

2024-07-01 17:13 UTC, yeseul106 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/dto/EventBridgeSenderRequest.java
> +            List<String> userIds, String title, String content, Category category, String deepLink, String webLink
네 맞습니다 ! 푸시 알림 서버로 요청이 들어갈 때는 header에 x-api-key를 첨부해야 하는데요 ! 

예약 발송의 경우, json 타입의 데이터에 해당 값을 넣은 형식으로 Header를 구성해서 페이로드에 담아주어야 하므로 해당 DTO 형식을 생성할 때, xApiKey 값도 같이 넣어주기 위해서 생성자로 받아서 처리 했습니다 !

2024-07-01 17:13 UTC, yeseul106 commented on operation-external/src/main/java/org/sopt/makers/operation/client/eventbridge/EventBridgeImpl.java
> +        try {
앗 이거 private 선언 해야하는데, 실수한 것 같네요 ! 발견 감사합니다 !! 수정해놓을게요 !!

2024-07-02 02:12 UTC, KWY0218 commented on operation-external/src/main/java/org/sopt/makers/operation/client/alarm/AlarmManager.java
> +    }
p3
혹시 이 곳은 함수 이름의 prefix로 post라고 명칭한 이유가 있을까요?!

2024-07-02 02:14 UTC, KWY0218 approved these changes
LGTM 입니다~! 
전체적으로 저는 좋습니다~!

2024-07-02 02:15 UTC, yeseul106 commented on operation-external/src/main/java/org/sopt/makers/operation/client/alarm/AlarmManager.java
> +    }
허허 논의 전 동규 리뷰 반영하다가 여기를 빼먹었네요 ㅎ 수정 하겠습니다 ~!~!

2024-07-07 22:49 UTC, yummygyudon approved these changes
저도 확인 완료했습니다!! :)
고생 많았어요~!!

2024-07-08 00:25 UTC, merged